spring.application.name=sivemor-app
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
db.name = sivemor
db.host = localhost
db.port = 3306
db.user = root
db.password = root
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=sivemorverificaciones@gmail.com
spring.mail.password=qvghiwgnhhlqndop
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
